GalOrrery/stream_mapper-pytorch

- src/stream_ml/pytorch/compat/__init__.py
- src/stream_ml/pytorch/compat/kde.py
Normalizing flow-like model using scipy KDE.
> scipy KDE model

- src/stream_ml/pytorch/builtin/__init__.py
- src/stream_ml/pytorch/builtin/_multinormal.py
- src/stream_ml/pytorch/builtin/_normal.py
- src/stream_ml/pytorch/builtin/_skewnormal.py
> skew normal distribution

- src/stream_ml/pytorch/builtin/__init__.py
> import compat in builtin

- src/stream_ml/pytorch/builtin/compat/kde.py
Optional transpose to KDE model.
> optional transpose

- src/stream_ml/pytorch/_connect/compat.py
- src/stream_ml/pytorch/_connect/funcs.py
- src/stream_ml/pytorch/prior/_track.py
- src/stream_ml/pytorch/utils.py
register the `get_namespace` dispatcher.
> register get_namespace dispatcher

- src/stream_ml/pytorch/_multi.py
- src/stream_ml/pytorch/params/bounds.py
Fixing a mistake in weight indexing in the Mixture Models.
> unpack full weights

- src/stream_ml/pytorch/builtin/compat/flow.py
> Add jacobean factor to the flow.

- src/stream_ml/pytorch/_base.py
- src/stream_ml/pytorch/prior/_track.py
> consolidate unpacking

- src/stream_ml/pytorch/_base.py
- src/stream_ml/pytorch/_multi.py
- src/stream_ml/pytorch/builtin/_isochrone.py
- src/stream_ml/pytorch/builtin/_sloped.py
- src/stream_ml/pytorch/builtin/compat/flow.py
- src/stream_ml/pytorch/utils.py
> Minimum of data names for transforming

- src/stream_ml/pytorch/builtin/_isochrone.py
From 2 to however many mags are used.
> correct shape for cov_dm

- .pre-commit-config.yaml
- src/stream_ml/pytorch/builtin/_exponential.py
- src/stream_ml/pytorch/builtin/_isochrone.py
- src/stream_ml/pytorch/builtin/_multinormal.py
- src/stream_ml/pytorch/builtin/_normal.py
- src/stream_ml/pytorch/builtin/_skewnormal.py
- src/stream_ml/pytorch/builtin/_sloped.py
- src/stream_ml/pytorch/builtin/compat/flow.py
- src/stream_ml/pytorch/builtin/compat/kde.py
- src/stream_ml/pytorch/prior/_track.py
> address mypy complaints

- src/stream_ml/pytorch/builtin/_stats/truncskewnorm.py
- src/stream_ml/pytorch/prior/_track.py
> fix call to clip

- src/stream_ml/pytorch/builtin/_exponential.py
Move exponential distribution to core.
> move Exponential to core

- src/stream_ml/pytorch/builtin/_isochrone.py
- src/stream_ml/pytorch/params/bounds.py
Following https://github.com/GalOrrery/stream_ml-core/pull/124
> Change parameter bounds scaler to initvar

- src/stream_ml/pytorch/params/bounds.py
This pull request is to address ...
Fixes #<Issue Number>
> xp on ParamBounds

- src/stream_ml/pytorch/_base.py
- src/stream_ml/pytorch/_connect/compat.py
- src/stream_ml/pytorch/params/bounds.py
A small improvement. Future PRs will adjust useage.
> Allow for non-inplace array_at

- src/stream_ml/pytorch/builtin/__init__.py
- src/stream_ml/pytorch/builtin/_isochrone.py
- Correctly normalize the isochrone when the gamma weights are not 1
- rename cluster mass function to stream mass functino
- allow it to vary over phi1
> Isochrone details

- src/stream_ml/pytorch/builtin/_isochrone.py
> fix shape in isochrone

- src/stream_ml/pytorch/_connect/__init__.py
- src/stream_ml/pytorch/_connect/nn_namespace.py
- src/stream_ml/pytorch/_multi.py
- src/stream_ml/pytorch/builtin/_isochrone.py
- src/stream_ml/pytorch/builtin/_multinormal.py
- src/stream_ml/pytorch/builtin/_skewnorm.py
- src/stream_ml/pytorch/builtin/_truncskewnorm.py
- src/stream_ml/pytorch/builtin/compat/flow.py
- src/stream_ml/pytorch/builtin/compat/kde.py
- src/stream_ml/pytorch/prior/__init__.py
- src/stream_ml/pytorch/prior/_track.py
- Applying cleanup from core
- isochrone improvements
> Cleanup and colors in isochrone

- src/stream_ml/pytorch/builtin/_isochrone.py
- src/stream_ml/pytorch/builtin/_multinormal.py
> Isochrone NNField is optional

- src/stream_ml/pytorch/builtin/_isochrone.py
Cannot convert negative pls to distance modulus. Unfortunately, need to clip.
> clip negative plx

- src/stream_ml/pytorch/_connect/__init__.py
- src/stream_ml/pytorch/_connect/scaler.py
> scaler-astype

- src/stream_ml/pytorch/prior/__init__.py
- src/stream_ml/pytorch/prior/_track.py
Improvements related to the control points and regions.
> Control region names

- src/stream_ml/pytorch/_base.py
- src/stream_ml/pytorch/builtin/__init__.py
- src/stream_ml/pytorch/builtin/_skewnorm.py
- src/stream_ml/pytorch/prior/_track.py
> clean up repr for array_namespace

- pyproject.toml
- src/stream_ml/pytorch/builtin/compat/__init__.py
- src/stream_ml/pytorch/builtin/compat/_flow.py
- src/stream_ml/pytorch/builtin/compat/nflow.py
- src/stream_ml/pytorch/builtin/compat/zuko.py
> Add flow for zuko package

- src/stream_ml/pytorch/builtin/_isochrone/utils.py
> Correct plx 2 distmod util

- src/stream_ml/pytorch/prior/_track.py
Turns out it already supports nan, but might as well clean up other stuff.
> clean up track prior

- src/stream_ml/pytorch/builtin/__init__.py
- src/stream_ml/pytorch/params/bounds.py
- src/stream_ml/pytorch/prior/__init__.py
- src/stream_ml/pytorch/prior/_track.py
> use better repr from core

- src/stream_ml/pytorch/params/bounds.py
use core repr in sigmoid bounds
> better repr in sigmoidbounds

- src/stream_ml/pytorch/_connect/__init__.py
- src/stream_ml/pytorch/_connect/xp_namespace.py
- src/stream_ml/pytorch/builtin/__init__.py
- src/stream_ml/pytorch/params/bounds.py
- src/stream_ml/pytorch/prior/__init__.py
> allow copy, pickle, etc

- src/stream_ml/pytorch/_base.py
- src/stream_ml/pytorch/_multi.py
- src/stream_ml/pytorch/builtin/__init__.py
Extending deepcopy to multi-models.
> setspace on multi-models

- src/stream_ml/pytorch/__init__.py
> more imports from core
